stages:
  - build
  - test
  - publish

build:
  stage: build
  image: node:14
  only:
    - tags
  cache:
    key: build-cache
    paths:
      - node_modules/
      - build/
      - lib/
      - .npmrc
    policy: push
  script:
    - echo "@fpmi:registry=https://gitlab.com/api/v4/packages/npm/">.npmrc
    - echo "//gitlab.com/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm ci
    - npm run build


test:
  stage: test
  image: node:14
  only:
    - tags
  cache:
    key: build-cache
    paths:
      - node_modules/
      - lib/
      - .npmrc
    policy: pull
  script:
    - echo "Nothing to test :)"


publish:
  stage: publish
  image: node:14
  only:
    - tags
  cache:
    key: build-cache
    paths:
      - node_modules/
      - lib/
      - .npmrc
    policy: pull
  script:
    - echo "@fpmi:registry=https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/">.npmrc
    - echo "//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm version --no-git-tag-version ${CI_COMMIT_TAG}
    - npm publish
